config/routes.rb
PersonalSite::Application.routes.draw do
  root to: 'content#home'

  match '/resume', to: 'content#resume'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_controller.rb
class ContentController < ApplicationController


  def resume
    pdf_filename = File.join(Rails.root, "app/assets/images/gesualdo_resume.pdf")
    send_file pdf_filename, :filename => "gesualdo_resume.pdf", :disposition => 'inline', :type => "application/pdf"
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/views/content/home.html.haml
#homepage
  .hire
    = link_to "Resume", resume_path

  .splash
    .splash_content.row
      .intro.col-12
        %p.center
          Hi, I'm
          %span.name Joe
          an
          %span.entrepreneur entrepreneur
          &
          %span.hacker coder
      .social_links.col-12
        .center
          = link_to image_tag('http://pushling.com/images/icons/github_icon.png'), 'https://github.com/joegesualdo'
          = link_to image_tag('http://pushling.com/images/icons/facebook_icon.png'), 'https://www.facebook.com/joepatrickgesualdo'
          = link_to image_tag('http://pushling.com/images/icons/linkedin_icon.png'), 'http://www.linkedin.com/in/joegesualdo'
          = link_to image_tag('http://images.talkingphonebook.com/images/localedge/icons/Black-Twitter.png'), 'https://twitter.com/joegesualdo'
  %section.middle.row
    %article.about.col-lg-6
      %h2 About me
      %p
        I’m a New York based Rails developer and entrepreneur with a passion and desire to build products
        that are extraordinary and lasting. My experience and interests are broad but my core talents are
        in design, development and implementation of web products.
    %article.experience.col-lg-5
      %h2 Developer
      %p
        I love to code and love the internet. My specialties lie in the development of "full stack" web
        frameworks. This includes everything from user-experience to database and all that lies between.
    %article.entrepreneur.col-lg-7
      %h2 Entrepreneur

      %p
        I'm always looking for creative ways to solve complicated problems.
        I have experience in both finance and technology, which provides me with a unique and valuable perspective
        when starting a company. My most recent business venture came in the form of a technology startup:
        =link_to "Homespree.", 'http://www.myhomespree.com'
        A company which leverages technology to improve the antiquated process of hiring a home improvement
        professional.

    %article.tech_skills.col-lg-4
      %h2 Technical Skills
      %span.blue Frameworks:
      Ruby on Rails, Backbone.js, Twitter Bootstrap.
      %span.yellow Front-end:
      HTML, HAML, CSS, SASS, Javascipt, Coffescript, JQUERY, AJAX, Responsive design.
      %span.aqua Version Control:
      Git.
      %span.red TDD:
      RSpec, Capybara, Guard.
      %span.orange Deployment:
      Heroku.










-#      #slider.swipe
-#        .swipe-wrap
-#          %div.row
-#            %image{src: 'http://myhomespree.com/assets/favicon.png', class: 'col-12'}
-#            .picturetext.col-6.col-sm-12.col-lg-6
-#
-#          %div
-#            %image{src: 'http://myhomespree.com/assets/favicon.png', class: 'col-12'}
-#            .picturetext.col-6.col-sm-12.col-lg-6
-#
-#          %div
-#            %image{src: 'http://myhomespree.com/assets/favicon.png', class: 'col-12'}
-#            .picturetext.col-6.col-sm-12.col-lg-6
-#
-#
-#-# JS for Slide. Needs to be on same page as view
-#:javascript
-#  window.mySwipe = new Swipe(document.getElementById('slider'), {
-#    startSlide: 1,
-#    speed: 400,
-#    auto: 7000,
-#    continuous: true,
-#    disableScroll: false,
-#    stopPropagation: false,
-#    callback: function(index, elem) {},
-#    transitionEnd: function(index, elem) {}
-#  });
-#

app/views/content/resume.html.haml
-#.row
-#  .resume_pdf.col-12
-#    %iframe{src:"/assets/gesualdo_resume.pdf", style: "width: 100%; height:700px;", frameborder: "0"}

/ #resume.row
/   %article.contact.col-lg-12
/     %h1 Joe Gesualdo
/     %h3 joegesualdo@gmail.com
/     %h3 732-977-9718

/   %article.objective.col-lg-12
/     %h1 Objective
/     %p
/       To build timeless, dynamic web products; to have fun, remain challenged,
/       and learn new things.
/   %article.company_type.col-lg-12
/     %h1 Looking for
/     %p
/       Looking to join a startup or a company with a startup culture. A place that
/       moves fast and where the team is passionate, smart, ambitious, fun and who love working
/       together. Having both worked at a stable fortune 500 company and starting my own business,
/       I understand the opportunity and challenges that come with working at an early stage startup.
/   %article.experience.col-lg-12
/     %h1 Experience
/     .homespree
/       %h3= link_to "Homespree, Inc", 'http://www.myhomespree.com'
/       %h5 Founder & COO
/       %ul
/         %li Developed online platform to radically improve the process of purchasing home services
/         %li Built architecture for myhomespree.com using Ruby on Rails, as well as many other technologies
/         %li Won 1st place out of 300 entrepreneurs at NYC Startup Weekend for business plan judged by industry-leading venture capitalists
/     .pwc
/       %h3 PwC
/       %h5 Valuation Associate
/       %ul
/         %li Determined the value of the Merger and Acquisition targets of our clients
/         %li Performed purchase price allocations, valued intangible assets and tested goodwill for impairment using various valuation methods: Discounted Cash Flow (DCF) method, Guideline Public Company Method, and Guideline Transactions method
/         %li Collaborated with fellow engineer to Ruby on Rails
/         %li Executed industry research, delved into the financials of target companies and develop complex financial models to value our clients' targets
/   %article.education.col-lg-12
/     %h1 Education
/     %h3 The College of New Jersey
/     %h5 Bachelors of Science, Finance
/     %ul
/       %li 3.62 GPA, Cum Laude, Honors
/   %article.tech_skills.col-lg-12
/     %h2 Technical Skills
/     Ruby on Rails, Backbone.js, Twitter Bootstrap
/     HTML, HAML, CSS, SASS, Javascipt, Coffescript, JQUERY, AJAX, Responsive design, Git, RSpec, Capybara, Guard,
/     Heroku, BASH, ZSH

app/views/layouts/application.html.haml
!!!
%html
%head
%title PersonalSite
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
= stylesheet_link_tag    "application", :media => "all"
= javascript_include_tag "application"
= csrf_meta_tags
%body
  = yield
  %footer.row
    .wrapper.col-12
      .row
        .links.center.col-12
          =mail_to('joegesualdo@gmail.com', "Email" )
          |
          =link_to "Resume", resume_path
        .made.col-12.center
          Made in Jersey, Refined in NY